UPDATE product SET images = JSON_ARRAY('/images/6-1-Apple-iPhone-15-Pro-256GB.jpg', '/images/6-1-2-Apple-iPhone-15-Pro-256GB.jpg') WHERE name = 'Apple iPhone 15 Pro 256GB' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/Xiaomi-Redmi-Note-13-Pro.jpg') WHERE name = 'Xiaomi Redmi Note 13 Pro 5G' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/6-1-2-Apple-MacBook-Pro-14-M3.jpg', '/images/8-1-Apple-MacBook-Pro-14-M3.jpg') WHERE name = 'Apple MacBook Pro 14 M3' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/Sony-WH-1000XM5-Headphones.jpg') WHERE name = 'Sony WH-1000XM5 Headphones' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/Apple-AirPods-Pro-2.jpg', '/images/Apple-AirPods-Pro-2.webp') WHERE name = 'Apple AirPods Pro 2' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/11-1-1-Apple-iPad-Air-11-M2.jpg', '/images/11-1-2-Apple-iPad-Air-11-M2-2.jpg') WHERE name = 'Apple iPad Air 11 M2' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/11-2-1-Huawei-MatePad-Pro-13-2-2.jpg', '/images/11-2-2-Huawei-MatePad-Pro-13-2-2.jpg') WHERE name = 'Huawei MatePad Pro 13.2' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/Sony-Alpha-A7-IV-Camera.jpg') WHERE name = 'Sony Alpha A7 IV Camera' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/13-2-Canon-EOS-R6-Mark-II.jpg') WHERE name = 'Canon EOS R6 Mark II' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/14-1-Apple-Watch-Series-9-1.jpg', '/images/14-2-apple-watch-series-9-3.png') WHERE name = 'Apple Watch Series 9' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/14-2-1-Huawei-Watch-GT-4-1.jpg', '/images/14-2-2-Huawei-Watch-GT-4-2.jpg') WHERE name = 'Huawei Watch GT 4' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/Logitech-G502-X-Wireless-Mouse-1.jpg') WHERE name = 'Logitech G502 X Wireless Mouse' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/56-2-1-echo-dot-5th-gen.jpg', '/images/56-2-2-echo-dot-5th-gen.png') WHERE name = 'Amazon Echo Dot 5th Gen' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/9-1-1-Uniqlo-AIRism-Cotton-T-Shirt.png', '/images/9-1-2-Uniqlo-AIRism-Cotton-T-Shirt.png') WHERE name = 'Uniqlo AIRism Cotton T-Shirt' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/10-2-1-Nike-Sportswear-Club-T-Shirt.png', '/images/10-2-2-Nike-Sportswear-Club-T-Shirt.png') WHERE name = 'Nike Sportswear Club T-Shirt' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/11-1-1-Zara-Satin-Midi-Dress.png') WHERE name = 'Zara Satin Midi Dress' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/9-2-1-H-M-Floral-Wrap-Dress.png', '/images/9-2-2-H-M-Floral-Wrap-Dress.png') WHERE name = 'H&M Floral Wrap Dress' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/15-1-1-Coach-Tabby-Shoulder-Bag.png', '/images/15-1-2-Coach-Tabby-Shoulder-Bag.png') WHERE name = 'Coach Tabby Shoulder Bag' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/16-2-1-Michael-Kors-Jet-Set-Crossbody.png', '/images/16-2-2-Michael-Kors-Jet-Set-Crossbody.png') WHERE name = 'Michael Kors Jet Set Crossbody' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/Atomic-Habits-Book.jpeg') WHERE name = 'Atomic Habits by James Clear' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/Zero-To-One-Book.jpeg') WHERE name = 'Zero to One by Peter Thiel' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/Coca-Cola-Original-330ml.jpeg') WHERE name = 'Coca-Cola Original 330ml' AND (images IS NULL OR JSON_LENGTH(images) = 0);
UPDATE product SET images = JSON_ARRAY('/images/36Red-Bull-Energy-Drink-250ml-1.jpeg') WHERE name = 'Red Bull Energy Drink 250ml' AND (images IS NULL OR JSON_LENGTH(images) = 0);
